"""Headless tests for omoikane/bin/wiki-lint.py and session-context.py. Run: python -m unittest discover -s tests"""
from __future__ import annotations

import importlib
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "omoikane" / "bin"))

from wikilib import Page  # noqa: E402

lint = importlib.import_module("wiki-lint")
context = importlib.import_module("session-context")


def page(slug: str, kind: str, **meta: object) -> Page:
    base: dict[str, object] = {"title": slug, "type": kind, "summary": "s", "tags": [], "created": "2026-09-15",
                               "updated": "2026-09-15", "sources": ["wiki/sources/x.md"]}
    base.update(meta)
    return Page(path=Path(f"/wiki/{slug}.md"), slug=slug, meta=base)


class CodePaths(unittest.TestCase):
    def test_missing_code_path_is_a_finding(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "keep.py").write_text("", encoding="utf-8")
            hub = page("hub", "concept", body="")
            hub.links = {"g"}
            g = page("g", "gotcha", code=["keep.py", "gone.py"])
            g.links = {"hub"}
            findings = lint.lint_pages([hub, g], Path(d))
        self.assertEqual(findings, ["/wiki/g.md: code path `gone.py` does not exist"])

    def test_new_types_accepted(self) -> None:
        a = page("a", "decision")
        b = page("b", "gotcha")
        a.links, b.links = {"b"}, {"a"}
        self.assertEqual(lint.lint_pages([a, b], Path(".")), [])


class CompactIndex(unittest.TestCase):
    INDEX = "# Index\n\nGenerated by x.\n\n## Decisions (1)\n\n- [[a]] — one\n\n## Sources (1)\n\n- [[s]] — two\n"

    def test_drops_header_keeps_sections(self) -> None:
        out = context.compact_index(self.INDEX, 12_000)
        self.assertTrue(out.startswith("## Decisions (1)"))
        self.assertIn("## Sources (1)", out)
        self.assertNotIn("Generated by", out)

    def test_truncates_at_section_boundary(self) -> None:
        out = context.compact_index(self.INDEX, 40)
        self.assertIn("## Decisions (1)", out)
        self.assertNotIn("## Sources (1)", out)
        self.assertIn("Index truncated", out)


if __name__ == "__main__":
    unittest.main()
