"""Headless tests for omoikane/bin/wiki-lint.py and session-context.py. Run: python -m unittest discover -s tests"""
from __future__ import annotations

import importlib
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "omoikane" / "bin"))

from wikilib import Page  # noqa: E402

lint = importlib.import_module("wiki-lint")
context = importlib.import_module("session-context")


def page(slug: str, kind: str, **meta: object) -> Page:
    base: dict[str, object] = {"title": slug, "type": kind, "summary": "s", "tags": [], "created": "2026-09-15",
                               "updated": "2026-09-15", "sources": ["wiki/sources/x.md"]}
    base.update(meta)
    return Page(path=Path(f"/wiki/{slug}.md"), slug=slug, meta=base)


class CodePaths(unittest.TestCase):
    def test_missing_code_path_is_a_finding(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "keep.py").write_text("", encoding="utf-8")
            hub = page("hub", "concept", body="")
            hub.links = {"g"}
            g = page("g", "gotcha", code=["keep.py", "gone.py"])
            g.links = {"hub"}
            findings = lint.lint_pages([hub, g], Path(d))
        self.assertEqual(findings, ["/wiki/g.md: code path `gone.py` does not exist"])

    def test_code_path_outside_repo_is_a_finding(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            repo = Path(d) / "repo"
            repo.mkdir()
            (Path(d) / "outside.py").write_text("", encoding="utf-8")
            g = page("g", "gotcha", code=["../outside.py"])
            hub = page("hub", "concept")
            hub.links, g.links = {"g"}, {"hub"}
            findings = lint.lint_pages([hub, g], repo)
        self.assertEqual(findings, ["/wiki/g.md: code path `../outside.py` does not exist"])

    def test_new_types_accepted(self) -> None:
        a = page("a", "decision")
        b = page("b", "gotcha")
        a.links, b.links = {"b"}, {"a"}
        self.assertEqual(lint.lint_pages([a, b], Path(".")), [])


class CompactIndex(unittest.TestCase):
    INDEX = "# Index\n\nGenerated by x.\n\n## Decisions (1)\n\n- [[a]] — one\n\n## Sources (1)\n\n- [[s]] — two\n"

    def test_drops_header_keeps_sections(self) -> None:
        out = context.compact_index(self.INDEX, 12_000)
        self.assertTrue(out.startswith("## Decisions (1)"))
        self.assertIn("## Sources (1)", out)
        self.assertNotIn("Generated by", out)

    def test_keeps_entries_of_a_section_larger_than_the_budget(self) -> None:
        index = "# Index\n\n## Decisions (3)\n\n- [[a]] — one\n- [[b]] — two\n- [[c]] — three\n\n## Sources (1)\n\n- [[s]] — x\n"
        out = context.compact_index(index, 50)
        self.assertIn("- [[a]] — one", out)
        self.assertNotIn("[[c]]", out)
        self.assertNotIn("## Sources", out)
        self.assertIn("Omitted by budget: Decisions 1, Sources 1. Read omoikane/index.md", out)

    def test_no_omitted_line_when_everything_fits(self) -> None:
        self.assertNotIn("Omitted", context.compact_index(self.INDEX, 12_000))


class PendingNotes(unittest.TestCase):
    def test_lists_undistilled_sessions_and_counts_review_items(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            omoikane = Path(d) / "omoikane"
            sessions = omoikane / "raw" / "inbox" / "sessions"
            sessions.mkdir(parents=True)
            (sessions / ".gitkeep").write_text("", encoding="utf-8")
            (sessions / "2026-09-02-bbbbbbbb.md").write_text("", encoding="utf-8")
            (sessions / "2026-09-01-aaaaaaaa.md").write_text("", encoding="utf-8")
            (omoikane / "_review.md").write_text("# Review queue\n\nIntro.\n\n- one\n- two\n", encoding="utf-8")
            out = context.pending_notes(omoikane)
        self.assertLess(out.index("2026-09-01-aaaaaaaa.md"), out.index("2026-09-02-bbbbbbbb.md"))
        self.assertIn("`omoikane/raw/inbox/sessions/2026-09-02-bbbbbbbb.md`", out)
        self.assertNotIn(".gitkeep", out)
        self.assertIn("2 open items in omoikane/_review.md", out)

    def test_empty_when_nothing_is_pending(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            omoikane = Path(d) / "omoikane"
            omoikane.mkdir()
            (omoikane / "_review.md").write_text("# Review queue\n\nIntro.\n", encoding="utf-8")
            self.assertEqual(context.pending_notes(omoikane), "")


if __name__ == "__main__":
    unittest.main()
