"""Headless tests for omoikane/bin/wiki-lint.py and session-context.py. Run: python -m unittest discover -s tests"""
from __future__ import annotations

import importlib
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "omoikane" / "bin"))

from wikilib import Page  # noqa: E402

lint = importlib.import_module("wiki-lint")
context = importlib.import_module("session-context")


def page(slug: str, kind: str, **meta: object) -> Page:
    base: dict[str, object] = {"title": slug, "type": kind, "summary": "s", "tags": [], "created": "2026-09-15",
                               "updated": "2026-09-15", "sources": ["wiki/sources/x.md"]}
    base.update(meta)
    return Page(path=Path(f"/wiki/{slug}.md"), slug=slug, meta=base)


class CodePaths(unittest.TestCase):
    def test_missing_code_path_is_a_finding(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / "keep.py").write_text("", encoding="utf-8")
            hub = page("hub", "concept", body="")
            hub.links = {"g"}
            g = page("g", "gotcha", code=["keep.py", "gone.py"])
            g.links = {"hub"}
            findings = lint.lint_pages([hub, g], Path(d))
        self.assertEqual(findings, ["/wiki/g.md: code path `gone.py` does not exist"])

    def test_code_path_outside_repo_is_a_finding(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            repo = Path(d) / "repo"
            repo.mkdir()
            (Path(d) / "outside.py").write_text("", encoding="utf-8")
            g = page("g", "gotcha", code=["../outside.py"])
            hub = page("hub", "concept")
            hub.links, g.links = {"g"}, {"hub"}
            findings = lint.lint_pages([hub, g], repo)
        self.assertEqual(findings, ["/wiki/g.md: code path `../outside.py` does not exist"])

    def test_new_types_accepted(self) -> None:
        a = page("a", "decision")
        b = page("b", "gotcha")
        a.links, b.links = {"b"}, {"a"}
        self.assertEqual(lint.lint_pages([a, b], Path(".")), [])

    def test_same_slug_in_two_folders_is_a_finding(self) -> None:
        a = page("x", "decision")
        b = page("x", "gotcha")
        a.path, b.path = Path("/wiki/decisions/x.md"), Path("/wiki/gotchas/x.md")
        a.links, b.links = {"x"}, {"x"}
        findings = lint.lint_pages([a, b], Path("."))
        self.assertEqual(findings, ["/wiki/gotchas/x.md: slug `x` is also /wiki/decisions/x.md; [[x]] is ambiguous"])


class StalePages(unittest.TestCase):
    CHANGED = {"src/a.py": "2026-09-20", "src/pkg/b.py": "2026-09-12", "src/pkg/c.py": "2026-09-18"}

    def test_code_committed_after_update_is_a_warning(self) -> None:
        g = page("g", "gotcha", updated="2026-09-15", code=["src/a.py"])
        self.assertEqual(lint.stale_pages([g], self.CHANGED), [
            "/wiki/g.md: `src/a.py` changed on 2026-09-20, after the page's `updated` 2026-09-15; "
            "check the page still matches the code"])

    def test_code_committed_on_or_before_update_is_fine(self) -> None:
        g = page("g", "gotcha", updated="2026-09-20", code=["src/a.py", "src/pkg/b.py"])
        self.assertEqual(lint.stale_pages([g], self.CHANGED), [])

    def test_directory_takes_its_newest_file(self) -> None:
        d = page("d", "decision", updated="2026-09-15", code=["src/pkg/"])
        self.assertEqual(len(lint.stale_pages([d], self.CHANGED)), 1)
        self.assertIn("changed on 2026-09-18", lint.stale_pages([d], self.CHANGED)[0])

    def test_last_changed_reads_git_history(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            repo = Path(d)
            git = ["git", "-C", d, "-c", "user.name=t", "-c", "user.email=t@t"]
            subprocess.run(["git", "init", "-q", d], check=True)
            (repo / "src").mkdir()
            (repo / "src" / "a.py").write_text("1", encoding="utf-8")
            (repo / "other.py").write_text("1", encoding="utf-8")
            subprocess.run([*git, "add", "."], check=True)
            env = {**os.environ, "GIT_COMMITTER_DATE": "2026-09-01T12:00:00Z", "GIT_AUTHOR_DATE": "2026-09-01T12:00:00Z"}
            subprocess.run([*git, "commit", "-q", "-m", "one"], check=True, env=env)
            (repo / "src" / "a.py").write_text("2", encoding="utf-8")
            env = {**os.environ, "GIT_COMMITTER_DATE": "2026-09-05T12:00:00Z", "GIT_AUTHOR_DATE": "2026-09-05T12:00:00Z"}
            subprocess.run([*git, "commit", "-q", "-am", "two"], check=True, env=env)
            changed = lint.last_changed(repo, ["src"])
        self.assertEqual(changed, {"src/a.py": "2026-09-05"})

    def test_last_changed_skips_git_without_code_paths(self) -> None:
        self.assertEqual(lint.last_changed(Path("/nonexistent"), []), {})


class CompactIndex(unittest.TestCase):
    INDEX = "# Index\n\nGenerated by x.\n\n## Decisions (1)\n\n- [[a]] — one\n\n## Sources (1)\n\n- [[s]] — two\n"

    def test_drops_header_keeps_sections(self) -> None:
        out = context.compact_index(self.INDEX, 12_000)
        self.assertTrue(out.startswith("## Decisions (1)"))
        self.assertIn("## Sources (1)", out)
        self.assertNotIn("Generated by", out)

    def test_truncates_at_section_boundary(self) -> None:
        out = context.compact_index(self.INDEX, 40)
        self.assertIn("## Decisions (1)", out)
        self.assertNotIn("## Sources (1)", out)
        self.assertIn("Index truncated", out)


if __name__ == "__main__":
    unittest.main()
